# Generated by Django 2.2 on 2021-05-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210502_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='nameofuser',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
